#!/usr/bin/env bash

# This is a part of the CI.
# Build: ./scripts/ci build-for-testing
# Test: ./scripts/ci test-without-building

set -e

# xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
DEVICE=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}')
SCHEME="GitHeart"
PROJECT="GitHeart.xcodeproj"
DESTINATION="platform=iOS Simulator,name=$DEVICE"

xcodebuild $1 -scheme "$SCHEME" -project "$PROJECT" -destination "$DESTINATION"
