#!/usr/bin/env bash

# This is a part of the CI.
# Build: ./scripts/ci build-for-testing
# Test: ./scripts/ci test-without-building

set -e

SCHEME="GitHeart"
PROJECT="GitHeart.xcodeproj"
DEVICE=$(
   xcodebuild -showdestinations -project "$PROJECT" -scheme "$SCHEME" |
   grep 'name:iPhone' | sed 's/.*name:\([^,}]*\).*/\1/' | head -1 | xargs echo
)
DESTINATION="platform=iOS Simulator,name=$DEVICE"

xcodebuild $1 \
   -project "$PROJECT" \
   -scheme "$SCHEME" \
   -destination "$DESTINATION" \
   -showBuildTimingSummary
