#!/usr/bin/env bash

export PATH="$PATH:/opt/homebrew/bin"
if command -v mint &> /dev/null; then
    git status -uall --porcelain | awk -f Scripts/git-changed-files.awk | grep -e '\(.*\).swift$' | while read line; do
        xcrun --sdk macosx mint run swiftformat  --swiftversion 5.0 "${line}";
    done
else
    echo "warning: mint is not installed, autoformat is disabled."
fi
