name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test using any available iPhone simulator
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'
      - name: Generate Env.swift
        run: |
          ./scripts/setup ci
      - name: Build
        run: |
          ./scripts/ci build-for-testing
      - name: Test
        run: |
          ./scripts/ci test-without-building
