name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Env.swift
        env:
          content: 'struct Env { let githubAccessToken = "" }'
        run: |
          echo "$content" > "GitHeart/Env.swift"
      - name: Build
        run: |
          ./scripts/build
      - name: Test
        run: |
          ./scripts/test_without_building
